clf

Bio_Control = uicontrol('Style', 'pushbutton', 'String', 'Bio-SMART','FontUnits','inches','FontSize',0.8,'Position', [720 700 450 150],...
    'Callback', 'GUI_BioCon_Main_Page');  
     NetLeak = uicontrol('Style', 'pushbutton', 'String', 'Net Leak','FontUnits','inches','FontSize',0.8,'Position', [720 300 450 150],...
        'Position', [720 300 450 150],...
        'Callback', 'GUI_NetLeak_Main_Page'); 