clf
%import_all
Bicon_raw_data
BoiCon_Liklihood_Indicator
 Analysis = uicontrol('Style', 'pushbutton', 'String', 'Analyze the data here',...
        'Position', [420 10 150 20],...
        'Callback', 'BoiCon_Calculation');
    Main_page =uicontrol('Style', 'pushbutton', 'String', 'Main Menu',...
        'Position', [820 10 150 20],...
        'Callback', 'button_testing');