%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Public\Documents\New folder\Data for all.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/12/15 15:49:40

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\Public\Documents\Smart Water Data Source\Data from Excel Files\Data for all.xlsx','Sheet1','A2:R30','',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,15);
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18]);
dates = dates(:,1);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),dates); % Find non-numeric cells
dates(R) = {NaN}; % Replace non-numeric Excel dates with NaN

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Winter2010_S1 = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
Days_PGLK = data(:,1);
MNFScaleDown = data(:,2);
MNFClean = data(:,3);
Days_NPGK = data(:,4);
ADV = data(:,5);
AC = data(:,6);
NADV = data(:,7);
ADVS1 = data(:,8);
ACS1 = data(:,9);
NADC = data(:,10);
ADVS2 = data(:,11);
ACS2 = data(:,12);
NADV1 = data(:,13);
Dates = cellVectors(:,1);
Days_BioCon = data(:,14);
Orginal = data(:,15);
Cleandata = data(:,16);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% Winter2010_S1=datenum(Winter2010_S1);

%% Clear temporary variables
clearvars data raw dates cellVectors R;