clf
Consumed_Data = uicontrol('Style', 'pushbutton', 'String', 'View Comsumed Data',...
        'Position', [50 10 150 20],...
        'Callback', 'VDMA_Consumed_data');  
     Distributed_Data = uicontrol('Style', 'pushbutton', 'String', 'View Distributed Data ',...
        'Position', [350 10 150 20],...
        'Callback', 'VDMA_Distributed_data');  
     Dis_Con = uicontrol('Style', 'pushbutton', 'String', 'View Both',...
        'Position', [650 10 150 20],...
        'Callback', 'VDMA_Combined_Both_data');  
     Back = uicontrol('Style', 'pushbutton', 'String', 'Back ',...
        'Position', [950 15 150 20],...
        'Callback', 'GUI_NetLeak_Main_Page');  
     Main_page =uicontrol('Style', 'pushbutton', 'String', 'Main Menu',...
        'Position', [1250 15 150 20],...
        'Callback', 'button_testing');
    